language: R
sudo: false
cache: packages
warnings_are_errors: false

os:
  - linux
  - osx

r:
  - oldrel
  - release
  - devel

script:
- R -e "install.packages (c ('roxygen2', 'dbplyr')); roxygen2::roxygenize ('.')"
- R CMD build .
- R CMD check *tar.gz
